### ISSUE TITLE
v8_0_11 throws "Command exited with error code: '-1073741512' and output"

### ISSUE THREAD

**Issue by jlabanca** [wix/wix-embedded-mysql#180] opened 2019-09-19 00:37 UTC
When using Version.v8_0_11, I see the error below. Everything works fine with version v5_7_27.

```
java.lang.RuntimeException: Command exited with error code: '-1073741512' and output: ''
	at com.wix.mysql.distribution.setup.ProcessRunner.resolveException(ProcessRunner.java:53)
	at com.wix.mysql.distribution.setup.ProcessRunner.run(ProcessRunner.java:38)
	at com.wix.mysql.distribution.setup.Mysql8Initializer.apply(Mysql8Initializer.java:33)
	at com.wix.mysql.distribution.Setup.apply(Setup.java:24)
	at com.wix.mysql.MysqldExecutable.start(MysqldExecutable.java:36)
	at com.wix.mysql.MysqldExecutable.start(MysqldExecutable.java:15)
	at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:108)
	at com.wix.mysql.EmbeddedMysql.<init>(EmbeddedMysql.java:47)
	at com.wix.mysql.EmbeddedMysql$Builder.start(EmbeddedMysql.java:169)
	at com.syndicloud.jsonsync.store.MySqlJsonSyncStoreTest.<init>(MySqlJsonSyncStoreTest.java:48)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
```

My config: 
```
  private final MysqldConfig config = MysqldConfig.aMysqldConfig(Version.v8_0_11) //
      .withPort(3306) //
      .build();

  private final EmbeddedMysql mysql = EmbeddedMysql.anEmbeddedMysql(config) //
      .start();
```

**Comment by viliusl** [comment] 2019-11-03 11:12
@jlabanca - closing for now. 8.0.17 was fixed. Can also be caused by one of https://github.com/wix/wix-embedded-mysql#known-issues

**Closed by viliusl** 2019-11-03 11:12 UTC

**Comment by steve-perkins** [comment] 2020-01-04 19:53
@viliusl:  I think this is still an outstanding issue, and not necessarily related to the 2013 Visual C++ Redistributable prerequisite called for in the README.

I've added more detail in a comment on issue #157, which is still in an "Open" state.
