### ISSUE TITLE
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

### ISSUE THREAD

**Issue by lanhuai** [wix/wix-embedded-mysql#57] opened 2016-07-08 04:57 UTC
The first `BankMapperTest` success everytime, but the second `PartnerMapperTest` fail everytime, cause by MySql Communications link failure.

``` java
package com.xxx.test.common;

import com.wix.mysql.EmbeddedMysql;
import com.wix.mysql.config.MysqldConfig;
import org.junit.AfterClass;
import org.junit.BeforeClass;

import static com.wix.mysql.EmbeddedMysql.*;
import static com.wix.mysql.ScriptResolver.*;
import static com.wix.mysql.config.Charset.*;
import static com.wix.mysql.config.MysqldConfig.*;
import static com.wix.mysql.distribution.Version.*;

public abstract class EmbeddedMySqlTest extends AbstractTransactionalJUnit4SpringContextTests {

    private static EmbeddedMysql embeddedMysql;

    @BeforeClass
    public static void initMySql() {

        MysqldConfig config = aMysqldConfig(v5_6_24)
                .withCharset(UTF8)
                .withPort(3356)
                .withUser("root", "root")
                .withTimeZone("Asia/Shanghai")
                .build();

        embeddedMysql = anEmbeddedMysql(config)
                .addSchema("db_dev",
                           classPathFile("db/001_init_schema.sql"),
                           classPathFile("db/002_init_data.sql")
                )
                .start();
    }

    @AfterClass
    public static void stopMySql() {
        if (embeddedMysql != null) {
            embeddedMysql.stop();
        }
    }

}
```

``` java
@ContextConfiguration(locations = {
        "classpath:/spring/app-context.xml"})
public class BankMapperTest extends EmbeddedMySqlTest {

    @Autowired
    private BankMapper bankMapper;

    @Test
    public void test(){
        Bank bank = bankMapper.selectByPrimaryKey("100");
        assertThat(bank.getName()).isEqualTo("邮储银行");
    }
}
```

``` java
@ContextConfiguration(locations = {
        "classpath:/spring/app-context.xml"})
public class PartnerMapperTest extends EmbeddedMySqlTest {


    @Autowired
    private PartnerMapper partnerMapper;

    @Test
    public void getAllPartner() throws Exception {
        Pagination pagination = new Pagination(1,10);
        List<Partner> partners = partnerMapper.getAllPartner(0,"1",pagination);
        assertNotNull(partners);
    }


    @Test
    public void getDetail() throws Exception {
        List<Partner> partners = partnerMapper.getDetail("1");
        assertNotNull(partners);
    }

}
```

```
-------------------------------------------------------------------------------
Test set: com.xxx.mapper.BankMapperTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 16.44 sec
```

```
-------------------------------------------------------------------------------
Test set: com.xxx.mapper.partner.PartnerMapperTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 9.879 sec <<< FAILURE!
getAllPartner(com.xxx.mapper.partner.PartnerMapperTest)  Time elapsed: 0.073 sec  <<< ERROR!
org.springframework.transaction.CannotCreateTransactionException: Could not open JDBC Connection for transaction; nested exception is com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 10,320 milliseconds ago.  The last packet sent successfully to the server was 16 milliseconds ago.
    at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:241)
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:372)
    at org.springframework.test.context.transaction.TransactionalTestExecutionListener$TransactionContext.startTransaction(TransactionalTestExecutionListener.java:583)
    at org.springframework.test.context.transaction.TransactionalTestExecutionListener.startNewTransaction(TransactionalTestExecutionListener.java:276)
    at org.springframework.test.context.transaction.TransactionalTestExecutionListener.beforeTestMethod(TransactionalTestExecutionListener.java:171)
    at org.springframework.test.context.TestContextManager.beforeTestMethod(TestContextManager.java:358)
    at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:73)
    at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:83)
    at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:231)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:88)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:174)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 10,320 milliseconds ago.  The last packet sent successfully to the server was 16 milliseconds ago.
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
    at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1127)
    at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3715)
    at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3604)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4155)
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2615)
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2776)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2832)
    at com.mysql.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:5357)
    at com.alibaba.druid.filter.FilterChainImpl.connection_setAutoCommit(FilterChainImpl.java:551)
    at com.alibaba.druid.filter.FilterAdapter.connection_setAutoCommit(FilterAdapter.java:984)
    at com.alibaba.druid.filter.FilterChainImpl.connection_setAutoCommit(FilterChainImpl.java:547)
    at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.setAutoCommit(ConnectionProxyImpl.java:430)
    at com.alibaba.druid.pool.DruidPooledConnection.setAutoCommit(DruidPooledConnection.java:674)
    at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:224)
    ... 33 more
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
    at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3161)
    at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3615)
    ... 45 more


```

**Comment by viliusl** [comment] 2016-07-08 05:47
Hi, several questions:
 - which version of wix-embedded-mysql are you using?
- did it work before and stopped working or is this how it behaves from the start?

Thanks,
V

**Comment by viliusl** [comment] 2017-06-01 06:33
closing as could not reproduce and no feedback:/

**Closed by viliusl** 2017-06-01 06:33 UTC
