### ISSUE TITLE
embedded mySql does not run under root user

### ISSUE THREAD

**Issue by noam-almog** [wix/wix-embedded-mysql#25] opened 2015-08-13 13:29 UTC
when running root user we will get an weird error.
we can either fix this by command line parameters --user ???
or by simple checking the running user and fail gracefully with a proper message (my preferred solution)
update docs to inform developers

CC: @orrsella

**Comment by viliusl** [comment] 2015-11-16 09:34
now it fails with `Caused by: java.lang.RuntimeException: mysql start failed with error: [ERROR] Fatal error: Please read "Security" section of the manual to find out how to run mysqld as root!`

We could add option to run it as some system user, like:

```
aMysqldConfig.withRunAsUser("root")
...
```

We could do that, but imho this case is weird in itself and current error message is quite descriptive.

I would mark it as a `no-fix` and would close id. WDYT?

**Comment by lpearson05** [comment] 2016-01-15 16:38
This is an issue people using Docker run into...

**Comment by viliusl** [comment] 2016-01-18 12:56
@lpearson05 what kind of dockerized set-up you have in mind? I mean I consider it important, just want to understand use-case better and maybe an idea for a failing test.

**Comment by lpearson05** [comment] 2016-01-19 04:14
Hi @viliusl, I actually finally figured out how to do a non-root setup (which was a major pain). I'm using embedded mysql in integration tests. It's not a problem for me anymore, but I totally understand why I see people asking about it. I was kind of just "chiming" in. Don't know the OP's situation.

The failing test would be to just run your tests in a docker container without any special configuration. The user executing the java app has to be root. That's all that's needed.

**Comment by Nimrod007** [comment] 2016-05-23 21:39
so lets say my dev machine is ubuntu and im running as root user, I cant use this ?

**Comment by viliusl** [comment] 2016-05-24 04:55
@Nimrod007 not currently.

It is possible to do that of course, but that involves:
 - checking current user id. if `id -u` is 0, then it's root;
 - setting additional `mysql` startup command (--user=root);
 - and this is applicable to *nix - not sure about windows yet.

So it's doable and might be even testable in ci as well (at least it should be possible to do this via additional build matrix configuration). Question is on actual demand. Docker case I can understand given you do it locally for test-environment management purposes. On ubuntu... :)

Anyway, do you really need it? Either PR or eventually I can pick it up, but no promises on timeline.

Cheers.

**Comment by viliusl** [comment] 2016-10-04 10:10
fixed by #88, released with version 2.0.4.

**Closed by viliusl** 2016-10-04 10:10 UTC
Labels: enhancement

**Comment by ylacaute** [comment] 2021-03-04 14:41
Hi, why can't we start embedded mysql as root ?
I am using Liquibase and try to create a schema but I don't have enough permission with the default user.

if (user.name.equals("root")) {
    throw new IllegalArgumentException("Usage of username 'root' is forbidden as it's reserved for system use");
   
Thank you.
